import type { EvolutionGene } from './types.js';

export const SEED_GENES: Omit<EvolutionGene, 'successCount' | 'failureCount' | 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'gene_fix_api_mismatch',
    category: 'repair',
    title: 'API 调用参数或端点错误修复',
    signalsMatch: ['api_misuse', 'error_pattern'],
    strategy: [
      '从错误信号中提取 API 端点和参数',
      '对比 API 文档或源码中的正确签名',
      '生成最小修改方案（改端点/加参数/改 HTTP 方法）',
      '验证修复后的 API 调用返回预期结果',
    ],
    validation: ['curl 测试修复后的 API 端点返回 2xx'],
    constraints: { maxFiles: 5 },
  },
  {
    id: 'gene_fix_env_var_leak',
    category: 'repair',
    title: '环境变量在后台/子 shell 中丢失修复',
    signalsMatch: ['error_pattern'],
    strategy: [
      '识别哪些变量在哪个 shell 上下文中丢失',
      '判断是 export 缺失、子进程不继承、还是后台 shell 隔离',
      '用硬编码值或 source 脚本替代环境变量引用',
    ],
    validation: ['在目标 shell 中 echo 变量确认有值'],
    constraints: { maxFiles: 3 },
  },
  {
    id: 'gene_fix_port_conflict',
    category: 'repair',
    title: 'EADDRINUSE 端口冲突修复',
    signalsMatch: ['error_pattern'],
    strategy: [
      '用 lsof -i :PORT 找到占用端口的进程',
      '判断是残留进程（kill）还是真实冲突（换端口）',
      '如果是 launchd 服务，检查 plist 配置',
    ],
    validation: ['启动服务后 curl 健康检查端点返回 200'],
    constraints: { maxFiles: 2 },
  },
  {
    id: 'gene_skill_ambiguity',
    category: 'optimize',
    title: 'SKILL 措辞歧义导致 Agent 误解',
    signalsMatch: ['skill_ambiguity', 'error_pattern'],
    strategy: [
      '从 Agent 的错误行为反推 SKILL 中的歧义来源',
      '明确区分容易混淆的概念（如 API 端点在不同 HTTP 方法下的含义）',
      '添加致命警告或 API 速查表防止再犯',
    ],
    validation: ['SKILL 文件格式正确且可被解析'],
    constraints: { maxFiles: 5 },
  },
  {
    id: 'gene_stale_reference',
    category: 'repair',
    title: '旧路径/旧名称残留清理',
    signalsMatch: ['stale_reference'],
    strategy: [
      '搜索代码库中对旧名称的引用',
      '批量替换为新名称',
      '验证没有遗漏',
    ],
    validation: ['grep 确认旧名称不再出现'],
    constraints: { maxFiles: 20 },
  },
  {
    id: 'gene_rule_gap',
    category: 'innovate',
    title: '规则缺口检测并补充',
    signalsMatch: ['rule_gap'],
    strategy: [
      '分析 GAP-REPORT 中未覆盖的操作模式',
      '从 ClawMem 经验中提取最佳实践',
      '生成新的 Cursor Rule 或 SKILL 补充段落',
    ],
    validation: ['新规则文件格式正确'],
    constraints: { maxFiles: 3 },
  },
  {
    id: 'gene_perf_polling_to_sse',
    category: 'optimize',
    title: '轮询改 SSE/WebSocket 推送',
    signalsMatch: ['perf_bottleneck', 'repeated_action'],
    strategy: [
      '识别 while-sleep 轮询模式',
      '替换为 SSE stream 或 WebSocket 订阅',
      '保留超时回退机制',
    ],
    validation: ['SSE 连接建立后能收到事件推送'],
    constraints: { maxFiles: 5 },
  },
  {
    id: 'gene_fix_launchd_deadlock',
    category: 'repair',
    title: 'launchd 定时任务死锁修复',
    signalsMatch: ['error_pattern', 'perf_bottleneck'],
    strategy: [
      '检查 launchd plist 的 StartInterval/StartCalendarInterval 配置',
      '分析任务间的数据依赖（如高频 ingest 吃掉低频 compile 的数据）',
      '调整触发条件（累积阈值/文件锁/状态文件）',
    ],
    validation: ['launchctl list 显示任务状态正常，日志确认触发'],
    constraints: { maxFiles: 3 },
  },
  {
    id: 'gene_fix_hub_session_timeout',
    category: 'repair',
    title: 'Hub Session 超时导致操作失败',
    signalsMatch: ['error_pattern', 'api_misuse'],
    strategy: [
      '检查 session TTL 和心跳间隔',
      '在长等待操作前后加心跳',
      '失败时自动重新注册',
    ],
    validation: ['长时间操作后 Hub API 仍返回成功'],
    constraints: { maxFiles: 3 },
  },
  {
    id: 'gene_optimize_error_handling',
    category: 'optimize',
    title: '静默错误改为显式处理',
    signalsMatch: ['error_pattern'],
    strategy: [
      '找到 catch {} / 2>/dev/null 等静默吞错模式',
      '判断哪些错误需要传播、哪些可以安全忽略',
      '为需要传播的错误添加日志或重抛',
    ],
    validation: ['故意触发错误后能看到日志输出'],
    constraints: { maxFiles: 10 },
  },
];
